# Generated by Django 5.2.17 on 2026-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_banner',
            name='title',
        ),
        migrations.AddField(
            model_name='main_banner',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='main_banners/'),
        ),
    ]
