# Generated by Django 6.1 on 2026-10-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0002_remove_main_banner_title_main_banner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='top_banners/')),
                ('nomi', models.TextField()),
                ('janr', models.TextField()),
                ('davlati', models.TextField()),
                ('yil', models.TextField()),
                ('tili', models.TextField()),
                ('davomiyligi', models.TextField()),
                ('yosh', models.TextField()),
                ('qisqa', models.TextField()),
                ('tavsifi', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='main_banner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
