# Generated by Django 6.1 on 2026-10-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0003_movie_alter_main_banner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_film',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yil',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yosh',
            field=models.IntegerField(),
        ),
    ]
