# Generated by Django 5.0.4 on 2026-10-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0004_movie_is_film_movie_is_serial_alter_movie_yil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Davlati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlati', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Janri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Yili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='janr',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tili',
        ),
        migrations.AlterField(
            model_name='main_banner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='movie',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uzmovi.catalog'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='davlati',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uzmovi.davlati'),
        ),
        migrations.AddField(
            model_name='movie',
            name='janri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uzmovi.janri'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uzmovi.yili'),
        ),
    ]
