# Generated by Django 5.0.4 on 2026-10-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzmovi', '0005_catalog_davlati_janri_yili_remove_movie_janr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='yil',
        ),
    ]
